/**
 * Human Design gate data — all 64 gates.
 * Each gate corresponds to an I Ching hexagram / Gene Key.
 * Data includes: name, theme, shadow, gift, siddhi, 6 line themes, daily reflection.
 */

export interface GateLine {
  name: string;
  theme: string;
}

export interface Gate {
  number: number;
  name: string;
  keyword: string;
  shadow: string;
  gift: string;
  siddhi: string;
  lines: [GateLine, GateLine, GateLine, GateLine, GateLine, GateLine];
  reflection: string;
  circuit: string;
}

export const GATES: Record<number, Gate> = {
  1: {
    number: 1,
    name: "The Creative",
    keyword: "Self-Expression",
    shadow: "Entropy",
    gift: "Freshness",
    siddhi: "Beauty",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Creative withdrawal as a source of power" },
      { name: "The Genius", theme: "The need for solitude to access higher creativity" },
      { name: "The Energy Field", theme: "The realization that creative energy is contagious" },
      { name: "The Role Model", theme: "Creative expression that inspires others effortlessly" },
      { name: "The Alchemist", theme: "Transforming the ordinary into something remarkable" },
      { name: "The Director", theme: "Mastery of giving form to the highest vision" },
    ],
    reflection: "Your creative expression is a gift to the world. Let it emerge naturally today.",
  },
  2: {
    number: 2,
    name: "The Receptive",
    keyword: "Direction",
    shadow: "Dislocation",
    gift: "Orientation",
    siddhi: "Unity",
    circuit: "Individual",
    lines: [
      { name: "The Innocent", theme: "Receptivity as a natural, unconditioned state" },
      { name: "The Pragmatist", theme: "Natural sense of direction without needing a map" },
      { name: "The Cave", theme: "Finding stillness to allow the right direction to emerge" },
      { name: "The Hermit", theme: "Inner knowing that guides without external reference" },
      { name: "The Savant", theme: "Natural genius recognized and called upon by others" },
      { name: "The Guru", theme: "Embodying unity that naturally orients those around you" },
    ],
    reflection: "Trust your inner compass. The right direction is already within you.",
  },
  3: {
    number: 3,
    name: "Ordering",
    keyword: "Innovation",
    shadow: "Chaos",
    gift: "Innovation",
    siddhi: "Innocence",
    circuit: "Individual",
    lines: [
      { name: "The Survivor", theme: "Resilience in the face of initial disorder" },
      { name: "The Mediator", theme: "Finding order by working through conflict patiently" },
      { name: "The Perpetual Child", theme: "Embracing the chaos as part of the creative process" },
      { name: "The Documentarian", theme: "Recording the journey through chaos for others to learn" },
      { name: "The Shaman", theme: "Using disorder as a doorway to transformation" },
      { name: "The Administrator", theme: "Natural ability to bring order out of chaos for the collective" },
    ],
    reflection: "Chaos is just order waiting to be discovered. You carry the seed of innovation.",
  },
  4: {
    number: 4,
    name: "Formulization",
    keyword: "Understanding",
    shadow: "Intolerance",
    gift: "Understanding",
    siddhi: "Forgiveness",
    circuit: "Collective",
    lines: [
      { name: "The Researcher", theme: "Gathering data before forming conclusions" },
      { name: "The Cynic", theme: "Testing ideas with healthy skepticism" },
      { name: "The Teacher", theme: "Sharing formulas that help others understand" },
      { name: "The Opportunist", theme: "Finding the most efficient solution for the collective" },
      { name: "The Academic", theme: "Systematizing knowledge for universal application" },
      { name: "The Genius", theme: "Transcending formulas to arrive at pure understanding" },
    ],
    reflection: "Understanding others begins with forgiving what you don't yet comprehend.",
  },
  5: {
    number: 5,
    name: "Fixed Patterns",
    keyword: "Patterns",
    shadow: "Victimization",
    gift: "Consistency",
    siddhi: "Timelessness",
    circuit: "Collective",
    lines: [
      { name: "The Nun/Monk", theme: "Devotion to a pattern as a path to mastery" },
      { name: "The Teacher", theme: "Modeling consistent behavior for others to follow" },
      { name: "The Anarchist", theme: "Testing the value of patterns by breaking them" },
      { name: "The Impostor", theme: "Learning discernment between useful and harmful patterns" },
      { name: "The Shaman", theme: "Changing the patterns that no longer serve the whole" },
      { name: "The Master", theme: "Living in timeless rhythm beyond habitual patterns" },
    ],
    reflection: "Your consistency creates ripples. The rhythms you hold shape those around you.",
  },
  6: {
    number: 6,
    name: "Conflict",
    keyword: "Friction",
    shadow: "Conflict",
    gift: "Diplomacy",
    siddhi: "Peace",
    circuit: "Collective",
    lines: [
      { name: "The Peacekeeper", theme: "Using personal example to diffuse conflict" },
      { name: "The Mediator", theme: "Finding the middle ground between opposing forces" },
      { name: "The Martyr", theme: "Learning that peace cannot be forced upon others" },
      { name: "The Opportunist", theme: "Stepping back to let conflict resolve itself naturally" },
      { name: "The Arbitrator", theme: "Bringing wisdom and impartiality to all disputes" },
      { name: "The Peacemaker", theme: "Embodying peace so completely that conflict cannot arise" },
    ],
    reflection: "Where there is friction, there is the possibility of profound warmth.",
  },
  7: {
    number: 7,
    name: "The Army",
    keyword: "Leadership",
    shadow: "Division",
    gift: "Guidance",
    siddhi: "Virtue",
    circuit: "Collective",
    lines: [
      { name: "The Authoritarian", theme: "Leading through strength in times of crisis" },
      { name: "The Democrat", theme: "Leadership through consensus and shared vision" },
      { name: "The Anarchist", theme: "Challenging authority to reveal what true leadership is" },
      { name: "The Abdicator", theme: "Leading from behind by giving power to others" },
      { name: "The General", theme: "Strategic leadership with long-term vision" },
      { name: "The Administrator", theme: "Guiding from a place of virtue and higher principle" },
    ],
    reflection: "True guidance serves the whole. Lead from your integrity today.",
  },
  8: {
    number: 8,
    name: "Holding Together",
    keyword: "Contribution",
    shadow: "Mediocrity",
    gift: "Style",
    siddhi: "Exquisiteness",
    circuit: "Individual",
    lines: [
      { name: "The Bohemian", theme: "Standing out by being authentically different" },
      { name: "The Monk", theme: "Inner alignment that makes contribution effortless" },
      { name: "The Guru", theme: "Leading others by modeling authenticity" },
      { name: "The Prodigy", theme: "Natural talent that draws others into coherence" },
      { name: "The Shaman", theme: "Contribution that transforms the collective field" },
      { name: "The Master", theme: "Exquisite uniqueness that elevates all around it" },
    ],
    reflection: "Your unique style IS your contribution. Don't dilute it.",
  },
  9: {
    number: 9,
    name: "The Taming Power of the Small",
    keyword: "Focus",
    shadow: "Inertia",
    gift: "Determination",
    siddhi: "Invincibility",
    circuit: "Collective",
    lines: [
      { name: "The Prodigal", theme: "The power of returning to focus after distraction" },
      { name: "The Disciplinarian", theme: "Sustained focus as a discipline and daily practice" },
      { name: "The Finalist", theme: "Concentration that leads to tangible results" },
      { name: "The Innovator", theme: "Focused attention that discovers new solutions" },
      { name: "The Specialist", theme: "Deep mastery through sustained, narrow focus" },
      { name: "The Master", theme: "Focus so total it becomes effortless presence" },
    ],
    reflection: "Small steps, sustained. Your determination today is your victory tomorrow.",
  },
  10: {
    number: 10,
    name: "Treading",
    keyword: "Behavior",
    shadow: "Self-Obsession",
    gift: "Naturalness",
    siddhi: "Being",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Behavior rooted in integrity and inner alignment" },
      { name: "The Hermit", theme: "Walking your own path regardless of judgment" },
      { name: "The Martyr", theme: "Honoring your path even under social pressure" },
      { name: "The Opportunist", theme: "Adapting behavior skillfully to context" },
      { name: "The Universal", theme: "Natural behavior that uplifts everyone around you" },
      { name: "The Role Model", theme: "Simply being yourself becomes a gift to the world" },
    ],
    reflection: "The most radical thing you can do today is simply be yourself.",
  },
  11: {
    number: 11,
    name: "Peace",
    keyword: "Ideas",
    shadow: "Obscurity",
    gift: "Idealism",
    siddhi: "Light",
    circuit: "Collective",
    lines: [
      { name: "The Peacemaker", theme: "Finding peace through the acceptance of duality" },
      { name: "The Philanthropist", theme: "Sharing ideas that benefit the collective" },
      { name: "The Realist", theme: "Grounding visionary ideas in practical reality" },
      { name: "The Student", theme: "Openness to new ideas as a form of peace" },
      { name: "The Philosopher", theme: "Ideas that illuminate the deeper nature of existence" },
      { name: "The Sage", theme: "Resting in the light beyond all ideas" },
    ],
    reflection: "Your ideas carry light. Share them — even one mind illuminated changes everything.",
  },
  12: {
    number: 12,
    name: "Standstill",
    keyword: "Articulation",
    shadow: "Vanity",
    gift: "Discrimination",
    siddhi: "Purity",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Silence as a sacred form of articulation" },
      { name: "The Aesthete", theme: "Choosing words with care and deep discernment" },
      { name: "The Rejected", theme: "Speaking truth even when it is unwelcome" },
      { name: "The Aristocrat", theme: "Expressing the highest through form and beauty" },
      { name: "The Reformer", theme: "Articulating a vision that transforms the status quo" },
      { name: "The Master", theme: "Pure expression that transmits beyond words" },
    ],
    reflection: "What you say today can shift a whole field. Choose your words with love.",
  },
  13: {
    number: 13,
    name: "The Listener",
    keyword: "Narrative",
    shadow: "Discord",
    gift: "Discernment",
    siddhi: "Empathy",
    circuit: "Individual",
    lines: [
      { name: "The Optimist", theme: "Holding the bigger story with hope and openness" },
      { name: "The Pessimist", theme: "Tempering narrative with honest assessment" },
      { name: "The Martyr", theme: "Carrying the collective's stories with compassion" },
      { name: "The Opportunist", theme: "Finding the healing thread within any story" },
      { name: "The Savior", theme: "Witnessing others' pain as a path to collective healing" },
      { name: "The Optimist", theme: "Deep empathy that transforms discord into harmony" },
    ],
    reflection: "Everyone carries a story worth hearing. Your listening today is an act of love.",
  },
  14: {
    number: 14,
    name: "Possession in Great Measure",
    keyword: "Capacity",
    shadow: "Compromise",
    gift: "Competence",
    siddhi: "Bounteousness",
    circuit: "Individual",
    lines: [
      { name: "The Steward", theme: "Using resources wisely in service of the whole" },
      { name: "The Servant", theme: "Skills offered freely in service to a greater vision" },
      { name: "The Philanthropist", theme: "Generosity that amplifies collective capacity" },
      { name: "The Bureaucrat", theme: "Managing resources efficiently and fairly" },
      { name: "The Plutocrat", theme: "Great capacity channeled for collective empowerment" },
      { name: "The Master", theme: "Boundless energy in service of life's highest expression" },
    ],
    reflection: "You have more than enough to give today. Share your energy freely.",
  },
  15: {
    number: 15,
    name: "Modesty",
    keyword: "Extremes",
    shadow: "Dullness",
    gift: "Magnetism",
    siddhi: "Florescence",
    circuit: "Individual",
    lines: [
      { name: "The Humanitarian", theme: "Embracing all rhythms without judgment" },
      { name: "The Extremist", theme: "Oscillating between extremes to find the center" },
      { name: "The Soothsayer", theme: "Sensing the rhythm beneath all apparent extremes" },
      { name: "The Wanderer", theme: "Going wherever life's flow leads without resistance" },
      { name: "The Activist", theme: "Channeling magnetic energy into collective change" },
      { name: "The Master", theme: "Natural florescence that lights up every environment" },
    ],
    reflection: "Life has its own rhythms. Your deepest power comes from flowing with them.",
  },
  16: {
    number: 16,
    name: "Enthusiasm",
    keyword: "Skills",
    shadow: "Indifference",
    gift: "Versatility",
    siddhi: "Mastery",
    circuit: "Collective",
    lines: [
      { name: "The Novice", theme: "Enthusiasm before skill — the courage to begin" },
      { name: "The Cynic", theme: "Testing enthusiasm with discernment" },
      { name: "The Independent", theme: "Developing skills on your own terms" },
      { name: "The Specialist", theme: "Deep enthusiasm that drives mastery in one area" },
      { name: "The Wizard", theme: "Versatile enthusiasm that makes all skills accessible" },
      { name: "The Master", theme: "True mastery achieved through sustained joyful practice" },
    ],
    reflection: "Enthusiasm is your signal. Follow it today and let skill emerge naturally.",
  },
  17: {
    number: 17,
    name: "Following",
    keyword: "Opinions",
    shadow: "Opinion",
    gift: "Far-Sightedness",
    siddhi: "Omniscience",
    circuit: "Collective",
    lines: [
      { name: "The Organizer", theme: "Structuring opinions to make them useful" },
      { name: "The Humanitarian", theme: "Opinions in service of the collective good" },
      { name: "The Realist", theme: "Tempering vision with grounded perception" },
      { name: "The Abdicator", theme: "Releasing opinions when they no longer serve" },
      { name: "The Reformer", theme: "Visionary opinion that challenges outdated thinking" },
      { name: "The Sage", theme: "Seeing beyond opinion into omniscient awareness" },
    ],
    reflection: "Your perspective matters. Hold it lightly — insight lives at the edge of opinion.",
  },
  18: {
    number: 18,
    name: "Work on What Has Been Spoiled",
    keyword: "Judgment",
    shadow: "Judgment",
    gift: "Integrity",
    siddhi: "Perfection",
    circuit: "Collective",
    lines: [
      { name: "The Conservative", theme: "Cautious correction of what has gone wrong" },
      { name: "The Collaborator", theme: "Working with others to restore what is broken" },
      { name: "The Innovator", theme: "Using what's broken as raw material for something new" },
      { name: "The Destroyer", theme: "The courage to fully dismantle before rebuilding" },
      { name: "The Reformer", theme: "Systemic correction that serves the collective" },
      { name: "The Sage", theme: "Resting in the perfection within all imperfection" },
    ],
    reflection: "There is perfection hidden inside every flaw. Look with gentler eyes today.",
  },
  19: {
    number: 19,
    name: "Approach",
    keyword: "Wanting",
    shadow: "Co-Dependence",
    gift: "Sensitivity",
    siddhi: "Sacrifice",
    circuit: "Tribal",
    lines: [
      { name: "The Hermit", theme: "Meeting your own needs before reaching out" },
      { name: "The Empath", theme: "Sensitivity that truly hears what others need" },
      { name: "The Martyr", theme: "Sacrifice made from love rather than neediness" },
      { name: "The Team Player", theme: "Needs met through genuine community" },
      { name: "The Shaman", theme: "Sensitivity used in service of collective healing" },
      { name: "The Master", theme: "Total surrender in service — needs dissolved in love" },
    ],
    reflection: "Sensitivity is your superpower. Let it open rather than close you today.",
  },
  20: {
    number: 20,
    name: "Contemplation",
    keyword: "Presence",
    shadow: "Superficiality",
    gift: "Self-Assurance",
    siddhi: "Presence",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Presence through sustained contemplative practice" },
      { name: "The Preacher", theme: "Speaking from presence rather than concept" },
      { name: "The Coward", theme: "The courage to be present despite fear" },
      { name: "The Opportunist", theme: "Presence that finds the opening in every moment" },
      { name: "The Shaman", theme: "Presence that transforms the energy of any space" },
      { name: "The Master", theme: "Simply being — without performance or pretense" },
    ],
    reflection: "The greatest gift you can offer today is your full, undivided presence.",
  },
  21: {
    number: 21,
    name: "Biting Through",
    keyword: "Control",
    shadow: "Control",
    gift: "Authority",
    siddhi: "Valor",
    circuit: "Tribal",
    lines: [
      { name: "The Servant", theme: "Using authority in service of the group" },
      { name: "The Strategist", theme: "Control through planning and careful execution" },
      { name: "The Fighter", theme: "Confronting what needs to be resolved directly" },
      { name: "The Hunter", theme: "Persistent authority that achieves its goals" },
      { name: "The Legislator", theme: "Authority that creates fair and just structures" },
      { name: "The Conqueror", theme: "Valor — the highest use of personal authority" },
    ],
    reflection: "Authority used in service of others is one of the most beautiful things.",
  },
  22: {
    number: 22,
    name: "Grace",
    keyword: "Openness",
    shadow: "Dishonor",
    gift: "Graciousness",
    siddhi: "Grace",
    circuit: "Individual",
    lines: [
      { name: "The Recluse", theme: "Withdrawing to protect emotional grace" },
      { name: "The Sympathizer", theme: "Emotional openness that honors others' feelings" },
      { name: "The Conformist", theme: "Learning when social grace requires yielding" },
      { name: "The Diplomat", theme: "Gracious behavior that transforms difficult situations" },
      { name: "The Planner", theme: "Preparing emotional conditions for grace to arise" },
      { name: "The Master", theme: "Grace as a living field — natural, effortless, contagious" },
    ],
    reflection: "Grace is not something you perform. It radiates from who you are.",
  },
  23: {
    number: 23,
    name: "Splitting Apart",
    keyword: "Assimilation",
    shadow: "Complexity",
    gift: "Simplicity",
    siddhi: "Quintessence",
    circuit: "Individual",
    lines: [
      { name: "The Hermit", theme: "Retreating to digest and simplify experience" },
      { name: "The Educator", theme: "Breaking complexity into simple, shareable truths" },
      { name: "The Anarchist", theme: "The gift of mutative ideas that split apart the old" },
      { name: "The Individualist", theme: "Trusting the uniqueness of your own perspective" },
      { name: "The Messenger", theme: "Simple truths delivered at the right moment" },
      { name: "The Master", theme: "The quintessence — the irreducible simplicity of truth" },
    ],
    reflection: "Simplicity is a superpower. Strip away the unnecessary today.",
  },
  24: {
    number: 24,
    name: "The Return",
    keyword: "Rationalization",
    shadow: "Addiction",
    gift: "Invention",
    siddhi: "Silence",
    circuit: "Individual",
    lines: [
      { name: "The Researcher", theme: "Patient return to the source of an idea" },
      { name: "The Penitent", theme: "Recognizing and correcting unhelpful patterns" },
      { name: "The Addict", theme: "Understanding what loops you pull toward compulsively" },
      { name: "The Revolutionary", theme: "New insight that arrives after deep processing" },
      { name: "The Inventor", theme: "Sudden creative breakthrough after quiet incubation" },
      { name: "The Master", theme: "Resting in the silence from which all invention arises" },
    ],
    reflection: "The mind that returns again and again eventually arrives somewhere new.",
  },
  25: {
    number: 25,
    name: "Innocence",
    keyword: "Spirit",
    shadow: "Constriction",
    gift: "Acceptance",
    siddhi: "Universal Love",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Spiritual practice as a return to innocence" },
      { name: "The Mystic", theme: "Direct experience of spirit beyond doctrine" },
      { name: "The Warrior", theme: "Fighting for love rather than personal interest" },
      { name: "The Shaman", theme: "Healing through the transmission of innocent love" },
      { name: "The Eternal Child", theme: "Natural love unconditioned by fear or expectation" },
      { name: "The Master", theme: "Universal love — seeing the divine in all things" },
    ],
    reflection: "There is a love in you that has never been wounded. Touch it today.",
  },
  26: {
    number: 26,
    name: "The Taming Power of the Great",
    keyword: "Egotism",
    shadow: "Pride",
    gift: "Artfulness",
    siddhi: "Invisibility",
    circuit: "Tribal",
    lines: [
      { name: "The Manipulator", theme: "The shadow of skill — using gifts for personal gain" },
      { name: "The Politician", theme: "Artful navigation of complex social terrain" },
      { name: "The Salesperson", theme: "The gift of making truth irresistible" },
      { name: "The Opportunist", theme: "Recognizing and seizing the right moment" },
      { name: "The Storyteller", theme: "Truth transmitted through artful narrative" },
      { name: "The Invisible Hand", theme: "Influence so pure it is no longer felt as pressure" },
    ],
    reflection: "The most powerful influence is the one you don't even notice.",
  },
  27: {
    number: 27,
    name: "Nourishment",
    keyword: "Caring",
    shadow: "Selfishness",
    gift: "Altruism",
    siddhi: "Selflessness",
    circuit: "Tribal",
    lines: [
      { name: "The Nurturer", theme: "Caring for others as a natural expression of love" },
      { name: "The Caretaker", theme: "Balanced giving — nourishing without depleting" },
      { name: "The Miser", theme: "Learning to receive as gracefully as you give" },
      { name: "The Generous One", theme: "Giving freely from genuine abundance" },
      { name: "The Savior", theme: "Altruism in service of the most vulnerable" },
      { name: "The Master", theme: "Selflessness — giving with no giver left behind" },
    ],
    reflection: "True nourishment begins with yourself. Fill up before you pour out.",
  },
  28: {
    number: 28,
    name: "Preponderance of the Great",
    keyword: "Struggle",
    shadow: "Purposelessness",
    gift: "Totality",
    siddhi: "Immortality",
    circuit: "Individual",
    lines: [
      { name: "The Masochist", theme: "Finding purpose in struggle rather than fleeing it" },
      { name: "The Monk", theme: "Sustained commitment through difficulty" },
      { name: "The Investigator", theme: "Going deep into the struggle to find its meaning" },
      { name: "The Gambler", theme: "Taking the risk that makes life feel worth living" },
      { name: "The Daredevil", theme: "Full aliveness through embracing mortality" },
      { name: "The Master", theme: "Transcending the fear of death — immortality in every moment" },
    ],
    reflection: "The struggle you're in is making you. Trust the weight you're carrying.",
  },
  29: {
    number: 29,
    name: "The Abysmal",
    keyword: "Commitment",
    shadow: "Half-Heartedness",
    gift: "Commitment",
    siddhi: "Devotion",
    circuit: "Collective",
    lines: [
      { name: "The Novice", theme: "Learning commitment through trial and error" },
      { name: "The Evaluator", theme: "Discerning what deserves your wholehearted yes" },
      { name: "The Compulsive", theme: "Breaking the pattern of saying yes out of fear" },
      { name: "The Monk", theme: "Depth of commitment as a spiritual practice" },
      { name: "The Mystic", theme: "Surrendering to what is calling you fully" },
      { name: "The Devotee", theme: "Total devotion — the self dissolved in commitment" },
    ],
    reflection: "A half-hearted yes is its own kind of no. What deserves all of you today?",
  },
  30: {
    number: 30,
    name: "The Clinging Fire",
    keyword: "Desire",
    shadow: "Desire",
    gift: "Lightness",
    siddhi: "Rapture",
    circuit: "Individual",
    lines: [
      { name: "The Victim", theme: "Recognizing desire as the root of suffering" },
      { name: "The Monk", theme: "Working with desire rather than against it" },
      { name: "The Martyr", theme: "Transformed desire that burns for others" },
      { name: "The Burnout", theme: "Learning the natural limits of fire's intensity" },
      { name: "The Hedonist", theme: "Desire embraced fully, leading to its transcendence" },
      { name: "The Master", theme: "Rapture — the fire of pure joy without object" },
    ],
    reflection: "What are you longing for? Desire is never wrong — only clinging is.",
  },
  31: {
    number: 31,
    name: "Influence",
    keyword: "Leadership",
    shadow: "Arrogance",
    gift: "Leadership",
    siddhi: "Humility",
    circuit: "Collective",
    lines: [
      { name: "The Manifestor", theme: "Leadership that initiates without waiting" },
      { name: "The Democrat", theme: "Leadership through collective voice and consensus" },
      { name: "The Opportunist", theme: "Leading by positioning at the right moment" },
      { name: "The Orator", theme: "Influence through the power of the spoken word" },
      { name: "The Populist", theme: "Leading by connecting with the needs of many" },
      { name: "The Master", theme: "Humble leadership — influence without ego" },
    ],
    reflection: "Real influence comes not from pushing your will, but from being deeply trustworthy.",
  },
  32: {
    number: 32,
    name: "Duration",
    keyword: "Continuity",
    shadow: "Failure",
    gift: "Preservation",
    siddhi: "Veneration",
    circuit: "Tribal",
    lines: [
      { name: "The Conservative", theme: "Preserving what is truly worth keeping" },
      { name: "The Visionary", theme: "Sensing what must change to ensure continuity" },
      { name: "The Traditionalist", theme: "Honoring the roots that give the tree its strength" },
      { name: "The Realist", theme: "Discernment between what to preserve and what to release" },
      { name: "The Shaman", theme: "Continuity through transformation, not stasis" },
      { name: "The Ancestor", theme: "Veneration — honoring the deep past as living wisdom" },
    ],
    reflection: "What is truly worth preserving? The answer will guide your energy today.",
  },
  33: {
    number: 33,
    name: "Retreat",
    keyword: "Privacy",
    shadow: "Forgetting",
    gift: "Mindfulness",
    siddhi: "Revelation",
    circuit: "Collective",
    lines: [
      { name: "The Hermit", theme: "Strategic withdrawal to gather power and clarity" },
      { name: "The Monk", theme: "Retreat as sacred practice" },
      { name: "The Concealer", theme: "Knowing what to share and what to protect" },
      { name: "The Shaman", theme: "Transforming experience in private before sharing" },
      { name: "The Educator", theme: "Returning from retreat to share what was learned" },
      { name: "The Sage", theme: "Revelation — the gift that emerges from deep stillness" },
    ],
    reflection: "Sometimes the most powerful thing you can do is step back.",
  },
  34: {
    number: 34,
    name: "The Power of the Great",
    keyword: "Power",
    shadow: "Force",
    gift: "Strength",
    siddhi: "Majesty",
    circuit: "Individual",
    lines: [
      { name: "The Bully", theme: "Raw power seeking direction" },
      { name: "The Subordinate", theme: "Strength that serves rather than dominates" },
      { name: "The Separatist", theme: "Independence as an expression of authentic power" },
      { name: "The Role Model", theme: "Strength that inspires rather than intimidates" },
      { name: "The Master", theme: "Power in service of what is right" },
      { name: "The Sage", theme: "Majestic power — strength without agenda" },
    ],
    reflection: "Your strength is beautiful when it serves something greater than itself.",
  },
  35: {
    number: 35,
    name: "Progress",
    keyword: "Change",
    shadow: "Hunger",
    gift: "Adventure",
    siddhi: "Boundlessness",
    circuit: "Collective",
    lines: [
      { name: "The Novice", theme: "The adventurer's excitement before the journey begins" },
      { name: "The Stoic", theme: "Accepting progress as it comes, without grasping" },
      { name: "The Technician", theme: "Progress through skill and practical application" },
      { name: "The Opportunist", theme: "Seizing the moment for meaningful progress" },
      { name: "The Adventurer", theme: "Experience for its own sake — the gift of pure aliveness" },
      { name: "The Master", theme: "Boundlessness — moving through life without limits" },
    ],
    reflection: "Adventure is not found — it is the quality of attention you bring to now.",
  },
  36: {
    number: 36,
    name: "The Darkening of the Light",
    keyword: "Crisis",
    shadow: "Turbulence",
    gift: "Humanity",
    siddhi: "Compassion",
    circuit: "Individual",
    lines: [
      { name: "The Innocent", theme: "Entering crisis without armor — raw openness" },
      { name: "The Stoic", theme: "Enduring darkness with quiet dignity" },
      { name: "The Martyr", theme: "Crisis that forges deep empathy for others" },
      { name: "The Opportunist", theme: "Finding the hidden gift within the crisis" },
      { name: "The Shaman", theme: "Moving through the underworld on behalf of many" },
      { name: "The Master", theme: "Boundless compassion born from having been to the depths" },
    ],
    reflection: "Every crisis is a doorway. You've been through dark before — and you've emerged.",
  },
  37: {
    number: 37,
    name: "The Family",
    keyword: "Equality",
    shadow: "Weakness",
    gift: "Equality",
    siddhi: "Tenderness",
    circuit: "Tribal",
    lines: [
      { name: "The Networker", theme: "Building bonds of belonging across difference" },
      { name: "The Mother/Father", theme: "Nurturing equality within the family unit" },
      { name: "The Martyr", theme: "Sacrifice for the good of the community" },
      { name: "The Facilitator", theme: "Creating conditions where all belong equally" },
      { name: "The Shaman", theme: "Transmitting the quality of belonging to the whole" },
      { name: "The Master", theme: "Tenderness — love without hierarchy or condition" },
    ],
    reflection: "Belonging is a gift you can give. Who needs to feel seen by you today?",
  },
  38: {
    number: 38,
    name: "Opposition",
    keyword: "Fight",
    shadow: "Stubbornness",
    gift: "Perseverance",
    siddhi: "Honor",
    circuit: "Individual",
    lines: [
      { name: "The Warrior", theme: "Fighting for what is worth fighting for" },
      { name: "The Loner", theme: "Standing alone with conviction" },
      { name: "The Anarchist", theme: "Opposition as a form of creative tension" },
      { name: "The Investigator", theme: "Persistence in pursuing what matters most" },
      { name: "The Shaman", theme: "Using opposition as a path to transcendence" },
      { name: "The Master", theme: "Honor — fighting only for the highest truth" },
    ],
    reflection: "Not all battles are worth fighting. Today, ask: what is truly worth my fire?",
  },
  39: {
    number: 39,
    name: "Obstruction",
    keyword: "Provocation",
    shadow: "Provocation",
    gift: "Dynamism",
    siddhi: "Liberation",
    circuit: "Individual",
    lines: [
      { name: "The Shaman", theme: "Using provocation to awaken dormant energy" },
      { name: "The Monk", theme: "Persisting through obstruction with quiet determination" },
      { name: "The Investigator", theme: "Understanding the root of the obstruction" },
      { name: "The Diplomat", theme: "Transmuting provocation into creative energy" },
      { name: "The Reformer", theme: "Obstructions as catalysts for systemic change" },
      { name: "The Master", theme: "Liberation — the freedom that comes from meeting every obstacle" },
    ],
    reflection: "The obstacle is the path. What is blocking you is also beckoning you.",
  },
  40: {
    number: 40,
    name: "Deliverance",
    keyword: "Aloneness",
    shadow: "Exhaustion",
    gift: "Resolve",
    siddhi: "Divine Will",
    circuit: "Tribal",
    lines: [
      { name: "The Monk", theme: "Solitude as deliverance from collective noise" },
      { name: "The Pragmatist", theme: "Recovery through practical self-care and rest" },
      { name: "The Team Player", theme: "Delivering on commitments with full resolve" },
      { name: "The Realist", theme: "Knowing when enough is enough" },
      { name: "The Reformer", theme: "Resolve that reshapes the conditions of work" },
      { name: "The Master", theme: "Divine will — acting from the deepest source of strength" },
    ],
    reflection: "Rest is not laziness. Replenishing yourself is how you honor everyone you serve.",
  },
  41: {
    number: 41,
    name: "Decrease",
    keyword: "Fantasy",
    shadow: "Fantasy",
    gift: "Anticipation",
    siddhi: "Emanation",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Compression of energy before the next cycle begins" },
      { name: "The Dreamer", theme: "Nurturing a dream before it can be expressed" },
      { name: "The Realist", theme: "Distinguishing fantasy from authentic longing" },
      { name: "The Magician", theme: "Channeling pure potential into creative form" },
      { name: "The Visionary", theme: "A new cycle beginning with fresh possibility" },
      { name: "The Master", theme: "Emanation — pure potential flowing into the world" },
    ],
    reflection: "Every new beginning starts with a contraction. What is quietly gathering in you?",
  },
  42: {
    number: 42,
    name: "Increase",
    keyword: "Growth",
    shadow: "Expectations",
    gift: "Detachment",
    siddhi: "Celebration",
    circuit: "Collective",
    lines: [
      { name: "The Martyr", theme: "Growth through sacrifice and letting go" },
      { name: "The Realist", theme: "Completing what was started without drama" },
      { name: "The Conservative", theme: "Stewarding what has grown with responsibility" },
      { name: "The Opportunist", theme: "Recognizing when growth is complete" },
      { name: "The Shaman", theme: "Celebrating the end of a cycle as its own gift" },
      { name: "The Master", theme: "Pure celebration — joy without object or occasion" },
    ],
    reflection: "Something in your life is ready to complete. Honor it before beginning again.",
  },
  43: {
    number: 43,
    name: "Breakthrough",
    keyword: "Insight",
    shadow: "Deafness",
    gift: "Insight",
    siddhi: "Epiphany",
    circuit: "Individual",
    lines: [
      { name: "The Visionary", theme: "Breakthrough insight that cannot yet be explained" },
      { name: "The Realist", theme: "Grounding insight into practical application" },
      { name: "The Shaman", theme: "Insight that transforms both self and collective" },
      { name: "The Monk", theme: "Waiting patiently for the right moment to share insight" },
      { name: "The Genius", theme: "Consistently at the edge of collective breakthrough" },
      { name: "The Master", theme: "Epiphany — direct knowing beyond the thinking mind" },
    ],
    reflection: "There's something you know that you haven't yet put into words. Trust it.",
  },
  44: {
    number: 44,
    name: "Coming to Meet",
    keyword: "Alertness",
    shadow: "Interference",
    gift: "Teamwork",
    siddhi: "Synergy",
    circuit: "Tribal",
    lines: [
      { name: "The Analyst", theme: "Pattern recognition as a survival instinct" },
      { name: "The Realist", theme: "Facing the truth of a situation without flinching" },
      { name: "The Loner", theme: "Independence as protection from unhealthy patterns" },
      { name: "The Opportunist", theme: "Alertness that creates powerful alliances" },
      { name: "The Shaman", theme: "Transforming collective patterns through presence" },
      { name: "The Master", theme: "Synergy — where the whole becomes greater than its parts" },
    ],
    reflection: "The patterns of the past don't have to repeat. Your alertness changes everything.",
  },
  45: {
    number: 45,
    name: "Gathering Together",
    keyword: "Gathering",
    shadow: "Dominance",
    gift: "Canvassing",
    siddhi: "Communion",
    circuit: "Tribal",
    lines: [
      { name: "The Ruler", theme: "Gathering from a place of authentic authority" },
      { name: "The Servant", theme: "Gathering in service of the collective" },
      { name: "The Barbarian", theme: "Learning the difference between gathering and grasping" },
      { name: "The Benefactor", theme: "Generous gathering that creates abundance for all" },
      { name: "The Shaman", theme: "Drawing people together for transformation" },
      { name: "The Master", theme: "Communion — gathering that dissolves separation" },
    ],
    reflection: "What are you gathering — and who are you gathering it for?",
  },
  46: {
    number: 46,
    name: "Pushing Upward",
    keyword: "Serendipity",
    shadow: "Seriousness",
    gift: "Serendipity",
    siddhi: "Ecstasy",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "The discipline of keeping the body as a sacred vessel" },
      { name: "The Clown", theme: "Joy and playfulness as a path to success" },
      { name: "The Shaman", theme: "Embodiment as a form of spiritual mastery" },
      { name: "The Opportunist", theme: "Being in the right place through physical awareness" },
      { name: "The Adventurer", theme: "Lucky encounters drawn by embodied aliveness" },
      { name: "The Master", theme: "Ecstasy — the body as a portal to the divine" },
    ],
    reflection: "Your body is an intelligence. What is it trying to tell you today?",
  },
  47: {
    number: 47,
    name: "Oppression",
    keyword: "Realization",
    shadow: "Oppression",
    gift: "Transmutation",
    siddhi: "Transfiguration",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Sitting with difficulty without reaching for an exit" },
      { name: "The Realist", theme: "Acknowledging the reality of oppression without collapse" },
      { name: "The Visionary", theme: "Insight born from sustained difficulty" },
      { name: "The Shaman", theme: "Using personal suffering as a doorway for collective healing" },
      { name: "The Pragmatist", theme: "Finding the practical gifts within limitation" },
      { name: "The Master", theme: "Transfiguration — the total alchemy of adversity into light" },
    ],
    reflection: "What feels like oppression today may be the pressure that creates a diamond.",
  },
  48: {
    number: 48,
    name: "The Well",
    keyword: "Depth",
    shadow: "Inadequacy",
    gift: "Resourcefulness",
    siddhi: "Wisdom",
    circuit: "Collective",
    lines: [
      { name: "The Incompetent", theme: "Learning that not knowing is the beginning of wisdom" },
      { name: "The Servant", theme: "Deep knowledge offered in service" },
      { name: "The Innovator", theme: "Resourcefulness born from deep familiarity" },
      { name: "The Monk", theme: "Sustained depth as a commitment" },
      { name: "The Teacher", theme: "Wisdom shared from the depths of lived experience" },
      { name: "The Sage", theme: "Pure wisdom — the deepest well that never runs dry" },
    ],
    reflection: "You are deeper than you know. Don't sell your knowing short today.",
  },
  49: {
    number: 49,
    name: "Revolution",
    keyword: "Principles",
    shadow: "Reaction",
    gift: "Revolution",
    siddhi: "Rebirth",
    circuit: "Tribal",
    lines: [
      { name: "The Revolutionary", theme: "The spark that initiates necessary change" },
      { name: "The Reformer", theme: "Principled revolution that improves the system" },
      { name: "The Partisan", theme: "Standing firm in principles despite opposition" },
      { name: "The Opportunist", theme: "Timing revolution to ensure its success" },
      { name: "The Shaman", theme: "Transformation that regenerates the whole" },
      { name: "The Master", theme: "Rebirth — total renewal that leaves nothing old intact" },
    ],
    reflection: "What outworn structures need to fall in your life? Revolution can be gentle.",
  },
  50: {
    number: 50,
    name: "The Cauldron",
    keyword: "Values",
    shadow: "Corruption",
    gift: "Equilibrium",
    siddhi: "Harmony",
    circuit: "Tribal",
    lines: [
      { name: "The Enforcer", theme: "Upholding values even under pressure" },
      { name: "The Gatekeeper", theme: "Maintaining the quality of what is held in the cauldron" },
      { name: "The Revolutionary", theme: "Changing the values when the old ones no longer serve" },
      { name: "The Cook", theme: "Skillful management of what nourishes the collective" },
      { name: "The Shaman", theme: "Values as a vessel for collective transformation" },
      { name: "The Master", theme: "Perfect harmony — the cauldron full, balanced, overflowing" },
    ],
    reflection: "Your values are your cauldron. What are you cooking for the people around you?",
  },
  51: {
    number: 51,
    name: "Arousing",
    keyword: "Shock",
    shadow: "Agitation",
    gift: "Initiative",
    siddhi: "Awakening",
    circuit: "Individual",
    lines: [
      { name: "The Reference Point", theme: "Using shock to establish identity and courage" },
      { name: "The Loner", theme: "Standing alone after the shock of individuation" },
      { name: "The Martyr", theme: "Shock that initiates others through personal sacrifice" },
      { name: "The Opportunist", theme: "Seizing the window opened by sudden change" },
      { name: "The Shaman", theme: "Shock as a tool of intentional awakening" },
      { name: "The Master", theme: "Pure awakening — beyond the shock into clarity" },
    ],
    reflection: "Whatever shook you was trying to wake something up. What stirred in you?",
  },
  52: {
    number: 52,
    name: "Keeping Still",
    keyword: "Stillness",
    shadow: "Stress",
    gift: "Restraint",
    siddhi: "Stillness",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Stillness as the foundation of all action" },
      { name: "The Peacemaker", theme: "Calming others through embodied stillness" },
      { name: "The Coach", theme: "Stillness that brings out the best in others" },
      { name: "The Shaman", theme: "Sacred stillness that opens the field of possibility" },
      { name: "The Hermit", theme: "Sustained stillness as a transformative practice" },
      { name: "The Master", theme: "Absolute stillness — the ground from which everything arises" },
    ],
    reflection: "In the gap between stimulus and response, your freedom lives. Pause today.",
  },
  53: {
    number: 53,
    name: "Development",
    keyword: "Beginnings",
    shadow: "Immaturity",
    gift: "Expansion",
    siddhi: "Emergence",
    circuit: "Collective",
    lines: [
      { name: "The Beginner", theme: "The courage to start without knowing the end" },
      { name: "The Analyst", theme: "Preparing thoroughly before beginning" },
      { name: "The Reformer", theme: "Developing what is already underway with care" },
      { name: "The Shaman", theme: "New beginnings that transform the collective field" },
      { name: "The Adventurer", theme: "Expansion through openness to the unknown" },
      { name: "The Master", theme: "Emergence — the new that cannot be predicted or planned" },
    ],
    reflection: "You don't need to see the whole path. Just the next step, taken with care.",
  },
  54: {
    number: 54,
    name: "The Marrying Maiden",
    keyword: "Ambition",
    shadow: "Greed",
    gift: "Aspiration",
    siddhi: "Ascension",
    circuit: "Tribal",
    lines: [
      { name: "The Underling", theme: "Rising through service and demonstrated competence" },
      { name: "The Shaman", theme: "Inner transformation as the source of outer advancement" },
      { name: "The Striver", theme: "Ambition in service of something greater than the ego" },
      { name: "The Dreamer", theme: "Aspiring toward the highest without attachment" },
      { name: "The Mystic", theme: "The highest aspiration as a form of spiritual longing" },
      { name: "The Master", theme: "Ascension — rising naturally as one's nature flowers" },
    ],
    reflection: "Aspiration is beautiful when it comes from the soul, not the wound. What's calling you?",
  },
  55: {
    number: 55,
    name: "Abundance",
    keyword: "Freedom",
    shadow: "Victimization",
    gift: "Freedom",
    siddhi: "Freedom",
    circuit: "Individual",
    lines: [
      { name: "The Spirit", theme: "Emotional freedom as the source of all abundance" },
      { name: "The Monk", theme: "Inner emotional work as the path to true freedom" },
      { name: "The Coward", theme: "The fear that prevents emotional freedom" },
      { name: "The Realist", theme: "Abundance through honest engagement with emotional truth" },
      { name: "The Visionary", theme: "Freedom that arises through creative emotional expression" },
      { name: "The Master", theme: "Absolute freedom — emotional sovereignty beyond all conditions" },
    ],
    reflection: "Freedom is not something you find outside yourself. It begins with how you meet this moment.",
  },
  56: {
    number: 56,
    name: "The Wanderer",
    keyword: "Stimulation",
    shadow: "Distraction",
    gift: "Enrichment",
    siddhi: "Intoxication",
    circuit: "Collective",
    lines: [
      { name: "The Refugee", theme: "Finding home within the journey itself" },
      { name: "The Perfectionist", theme: "Curiosity refined by discernment" },
      { name: "The Storyteller", theme: "Weaving experiences into narratives that enrich others" },
      { name: "The Shaman", theme: "The sacred wanderer — moving between worlds" },
      { name: "The Adventurer", theme: "Experiences gathered in service of collective enrichment" },
      { name: "The Master", theme: "Intoxication with existence — every moment its own reward" },
    ],
    reflection: "Every experience, no matter how small, is nourishment. What have you noticed today?",
  },
  57: {
    number: 57,
    name: "The Gentle",
    keyword: "Intuition",
    shadow: "Unease",
    gift: "Intuition",
    siddhi: "Clarity",
    circuit: "Collective",
    lines: [
      { name: "The Monk", theme: "Quiet intuitive attunement through stillness" },
      { name: "The Pragmatist", theme: "Intuition applied practically to daily life" },
      { name: "The Coward", theme: "Learning to trust intuition over logic" },
      { name: "The Opportunist", theme: "Following intuitive nudges toward right timing" },
      { name: "The Shaman", theme: "Intuition as a form of collective sensitivity" },
      { name: "The Master", theme: "Perfect clarity — seeing directly without filters" },
    ],
    reflection: "Your gut knows before your mind does. What is it quietly telling you today?",
  },
  58: {
    number: 58,
    name: "The Joyous",
    keyword: "Joy",
    shadow: "Dissatisfaction",
    gift: "Vitality",
    siddhi: "Bliss",
    circuit: "Collective",
    lines: [
      { name: "The Lover of Life", theme: "Joy as a natural response to being alive" },
      { name: "The Coach", theme: "Inspiring vitality in others through your own aliveness" },
      { name: "The Reformer", theme: "Improving life because you love it, not because you hate it" },
      { name: "The Shaman", theme: "Joy as a frequency that heals the collective" },
      { name: "The Adventurer", theme: "Vitality through full engagement with experience" },
      { name: "The Master", theme: "Pure bliss — joy without cause, without end" },
    ],
    reflection: "Joy is not something to pursue. It is what remains when you stop resisting what is.",
  },
  59: {
    number: 59,
    name: "Dispersion",
    keyword: "Sexuality",
    shadow: "Dishonesty",
    gift: "Intimacy",
    siddhi: "Transparency",
    circuit: "Tribal",
    lines: [
      { name: "The Seducer", theme: "Breaking down barriers through natural magnetism" },
      { name: "The Shaman", theme: "Sacred intimacy as a doorway to transcendence" },
      { name: "The Monk", theme: "Boundaries honored as a form of deep respect" },
      { name: "The Opportunist", theme: "Intimacy through authentic self-revelation" },
      { name: "The Romantic", theme: "Deep emotional intimacy as the foundation of union" },
      { name: "The Master", theme: "Transparency — the dissolution of all walls between self and other" },
    ],
    reflection: "True intimacy begins with being honest with yourself.",
  },
  60: {
    number: 60,
    name: "Limitation",
    keyword: "Realism",
    shadow: "Limitless",
    gift: "Realism",
    siddhi: "Justice",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Accepting limitation as the container of all growth" },
      { name: "The Realist", theme: "Clear-eyed assessment of what is and isn't possible" },
      { name: "The Martyr", theme: "Working within limitation with grace and creativity" },
      { name: "The Reformer", theme: "Changing systems by working within their constraints" },
      { name: "The Shaman", theme: "Limitation transcended through full acceptance" },
      { name: "The Master", theme: "Justice — the perfect balance of what is and what is possible" },
    ],
    reflection: "Constraints are not your enemy. They are the banks that give the river its power.",
  },
  61: {
    number: 61,
    name: "Inner Truth",
    keyword: "Mystery",
    shadow: "Psychosis",
    gift: "Inspiration",
    siddhi: "Sanctity",
    circuit: "Individual",
    lines: [
      { name: "The Monk", theme: "Inner truth accessed through sustained contemplation" },
      { name: "The Mystic", theme: "Direct experience of inner truth beyond language" },
      { name: "The Researcher", theme: "Investigating the mystery without needing resolution" },
      { name: "The Dreamer", theme: "Inspired by truths that arrive from beyond the rational" },
      { name: "The Visionary", theme: "Sharing inner truth in ways that awaken others" },
      { name: "The Master", theme: "Sanctity — resting in the holy ground of what is unknowable" },
    ],
    reflection: "Something true is alive in you that cannot be fully explained. Trust it anyway.",
  },
  62: {
    number: 62,
    name: "Preponderance of the Small",
    keyword: "Detail",
    shadow: "Intellectualism",
    gift: "Precision",
    siddhi: "Impeccability",
    circuit: "Collective",
    lines: [
      { name: "The Analyst", theme: "Precision through careful observation of detail" },
      { name: "The Researcher", theme: "Deep attention to facts before forming conclusions" },
      { name: "The Monk", theme: "Attending to the small as a practice of mindfulness" },
      { name: "The Pragmatist", theme: "Details in service of effective action" },
      { name: "The Teacher", theme: "Precision that makes complex things clear and accessible" },
      { name: "The Master", theme: "Impeccability — flawless attention as a form of love" },
    ],
    reflection: "The details are where the sacred lives. Pay attention to the small today.",
  },
  63: {
    number: 63,
    name: "After Completion",
    keyword: "Doubt",
    shadow: "Doubt",
    gift: "Inquiry",
    siddhi: "Truth",
    circuit: "Collective",
    lines: [
      { name: "The Monk", theme: "Resting in uncertainty without needing resolution" },
      { name: "The Realist", theme: "Honest inquiry that follows the evidence" },
      { name: "The Skeptic", theme: "Doubt used as a precision instrument" },
      { name: "The Visionary", theme: "Questions that open new dimensions of understanding" },
      { name: "The Researcher", theme: "Sustained inquiry as a form of devotion to truth" },
      { name: "The Master", theme: "Truth — arrived at through every doubt, every question" },
    ],
    reflection: "Your doubts are not obstacles. They are the questions that will lead you to what's real.",
  },
  64: {
    number: 64,
    name: "Before Completion",
    keyword: "Confusion",
    shadow: "Confusion",
    gift: "Imagination",
    siddhi: "Luminosity",
    circuit: "Collective",
    lines: [
      { name: "The Monk", theme: "Sitting with confusion as a sacred transitional state" },
      { name: "The Realist", theme: "Acknowledging what is unresolved without collapse" },
      { name: "The Visionary", theme: "Imagination as the bridge from confusion to clarity" },
      { name: "The Pragmatist", theme: "Making peace with incompleteness" },
      { name: "The Dreamer", theme: "Confusion as the compost from which vision grows" },
      { name: "The Master", theme: "Luminosity — light in the darkness before it fully breaks" },
    ],
    reflection: "You don't need to have it all figured out. The light is already gathering.",
  },
};

export function getGate(gateNumber: number): Gate {
  return GATES[gateNumber];
}
